# DataSource
spring.datasource.url = jdbc:mysql://localhost:3306/academy?useTimezone=true&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password =
spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1

# JPA
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.show_sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

# Thymeleaf
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Twilio Configurações
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE_NUMBER}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contix362@gmail.com
spring.mail.password=${SENHA_APP_GMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true